// Mocks generated by Mockito 5.4.6 from annotations
// in embutido_tracker/test/mocks/data_source_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:embutido_tracker/domain/entity/user.dart' as _i2;
import 'package:embutido_tracker/domain/sources/user_remote_source.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteSource extends _i1.Mock implements _i3.UserRemoteSource {
  MockUserRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.User> getUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i4.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#getUser, [userId])),
            ),
          )
          as _i4.Future<_i2.User>);

  @override
  _i4.Future<void> uploadAvatar({
    required String? userId,
    _i5.Uint8List? imageBytes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadAvatar, [], {
              #userId: userId,
              #imageBytes: imageBytes,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateUser({required String? userId, String? userName}) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [], {
              #userId: userId,
              #userName: userName,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
