// Mocks generated by Mockito 5.4.6 from annotations
// in embutido_tracker/test/mocks/service_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i6;

import 'package:embutido_tracker/core/services/image_service.dart' as _i5;
import 'package:embutido_tracker/core/services/logger_service.dart' as _i4;
import 'package:embutido_tracker/domain/services/auth_service.dart' as _i2;
import 'package:embutido_tracker/domain/services/avatar_cache_service.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<String?> get currentUserIdStream =>
      (super.noSuchMethod(
            Invocation.getter(#currentUserIdStream),
            returnValue: _i3.Stream<String?>.empty(),
          )
          as _i3.Stream<String?>);

  @override
  _i3.Future<void> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> signUp({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [LoggerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggerService extends _i1.Mock implements _i4.LoggerService {
  MockLoggerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void debug(String? message) => super.noSuchMethod(
    Invocation.method(#debug, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void info(String? message) => super.noSuchMethod(
    Invocation.method(#info, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void warn(String? message) => super.noSuchMethod(
    Invocation.method(#warn, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void error(String? message) => super.noSuchMethod(
    Invocation.method(#error, [message]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ImageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageService extends _i1.Mock implements _i5.ImageService {
  MockImageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Uint8List normalizeToPng(_i6.Uint8List? imageBytes) =>
      (super.noSuchMethod(
            Invocation.method(#normalizeToPng, [imageBytes]),
            returnValue: _i6.Uint8List(0),
          )
          as _i6.Uint8List);
}

/// A class which mocks [AvatarCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAvatarCacheService extends _i1.Mock
    implements _i7.AvatarCacheService {
  MockAvatarCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> getAvatarUrl(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getAvatarUrl, [userId]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> invalidate(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#invalidate, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> invalidateAll() =>
      (super.noSuchMethod(
            Invocation.method(#invalidateAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
